name: Build and Release Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    env:
      GOARCH: ${{ matrix.arch }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v -o myprogram-${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myprogram-${{ matrix.os }}-${{ matrix.arch }}
        path: myprogram-${{ matrix.os }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          myprogram-macos-latest-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
